[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

regex = "1"
itertools = "0.10"   
colored = "2"
rayon = "1.6.0"
gen-iter = "0.2.1"